name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug] "
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill in the details below to help us investigate the issue.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe what you expected to happen and what actually happened.
      placeholder: Clearly describe the bug or problem.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Run the command '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: I expected the app to...

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or logs
      description: If applicable, add screenshots or terminal logs to help explain your problem.
      placeholder: Paste logs or upload screenshots here.

  - type: input
    id: os
    attributes:
      label: Operating System (Optional)
      placeholder: e.g. macOS 13.5, Ubuntu 22.04, Windows 11

  - type: input
    id: zsh-version
    attributes:
      label: Zsh Version (Optional)
      placeholder: e.g. 5.9, 5.8.1

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context (Optional)
      description: Add any other context about the problem here.
