name: Feature Request
description: Suggest an idea to improve this project
title: "[Feature] "
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: input
    id: feature-summary
    attributes:
      label: Feature summary
      description: What is the feature or improvement?
      placeholder: Add a short and clear description here.
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Why do you need this feature? How would it help you or others?
      placeholder: Describe your use case or problem this would solve.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I tried doing X but it doesn't quite solve it...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context (Optional)
      description: Add any other context or screenshots here.
